import React from 'react';
import './feature.css';
import FeatureCard from '../common/FeatureCard';
import select from '../../assets/select.png';
import search from '../../assets/search.png';
import standout from '../../assets/standout.png';
import Grid from '@mui/material/Grid';

export default function Feature() {
  const features = [
    {
      src: search,
      alt: 'Search',
      title: 'Search',
      body: `Simply add a keyword or a term related to your business 
    in the slogan maker search box. Wait for the magic to happen.`,
    },
    {
      src: select,
      alt: 'Select',
      title: 'Select',
      body: `Choose from thousands of options generated by the 
      slogan maker that fit your needs.`,
    },
    {
      src: standout,
      alt: 'Standout',
      title: 'Stand Out',
      body: `Congrats on your new slogan. 
      It's time to win the world!`,
    },
  ];
  return (
    <div className="featureBg">
      <Grid container spacing={2} display="flex" direction="row">
        {features.map((feature) => {
          const { src, alt, title, body } = feature;
          return (
            <Grid item xs={12} md={4} key={title}>
              <FeatureCard
                src={src}
                title={title}
                body={body}
                alt={alt}
                key={title}
              />
            </Grid>
          );
        })}
      </Grid>
    </div>
  );
}
